$ANSIBLE_VAULT;1.1;AES256
38643739646430393439373430633362393734636263383238333932363031666239646562376661
3839343336363464663664623238373433333534633338610a663138636561356337313330643965
34333034366136363262333237353839316464643530616432306534373334323932343665616134
3764363135373131650a366335373864393561333535336134316464636331663764616239623066
30323363336233386333333966646261313833626364643564383431616362333835373230336630
32616361366331373863306332383965366662303163623735616130316262373863386530323666
643365343330643737666634333231366337
