lint:
  stage: lint
  before_script:
    - echo "Проверяем код линтерами..."
    - docker --version
  script:
    - docker-compose -f docker-compose.test.yml up -d --build
    - sleep 15

    # 1. Сначала автоматически форматируем
    - docker exec app poetry run black .
    
    # 2. Затем проверяем, что все ок (должно пройти)
    - docker exec app poetry run black --check .
    
    - docker exec app poetry run flake8 .
    - docker exec app poetry run mypy . --config-file mypy.ini || true
    - docker exec app poetry run isort --check-only .
  after_script:
    - docker-compose -f docker-compose.test.yml down