stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Тесты прошли, деплоим продакшен..."

    - docker compose down --remove-orphans
    - docker compose up -d --build

    - sleep 10
    - docker compose ps
    - echo "Деплой успешно завершен!"
  only:
    - master