stages:
  - lint

lint:
  stage: lint
  before_script:
    - echo "Проверяем код линтерами..."
    - docker --version
  script:
    - docker-compose -f docker-compose.test.yml up -d --build
    - sleep 15

    - docker exec app poetry run black .

    - docker exec app poetry run black --check .

    - docker exec app poetry run flake8 .
    - docker exec app poetry run mypy .
    - docker exec app poetry run isort .
  after_script:
    - docker-compose -f docker-compose.test.yml down