stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - echo "Запускаем тесты ..."
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f docker-compose.test.yml up -d --build
    - sleep 30
    - docker exec -T app poetry run python manage.py test payouts
  after_script:
    - docker-compose -f docker-compose.test.yml down
  artifacts:
    when: always
    paths:
      - test-reports/
    expire_in: 1 week

deploy:
  stage: deploy
  needs: ["test"]
  script:
    - echo "Тесты прошли, деплоим продакшен..."

    - docker-compose -f docker-compose.prod.yml down --remove-orphans
    - docker-compose -f docker-compose.prod.yml up -d --build

    - sleep 10
    - docker-compose -f docker-compose.prod.yml ps
    - echo "Деплой успешно завершен!"
  only:
    - master