stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - docker --version
  script:
    - echo "Тесты прошли, дпом продакшен..."
    - echo "Деплой успешно завершен!"
  tags:
    - deploy
