stages:
  - lint

lint:
  stage: lint
  before_script:
    - echo "Проверяем код линтерами..."
    - docker --version
  script:
    - docker-compose -f docker-compose.test.yml up -d --build
    - sleep 15

    - docker exec -T app poetry run black --check .

    - docker exec -T app poetry run flake8 .

    - docker exec -T app poetry run mypy . --config-file mypy.ini || true

    - docker exec -T app poetry run isort --check-only .
  after_script:
    - docker-compose -f docker-compose.test.yml down
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"