stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Тесты прошли, деплоим продакшен..."

    - docker run hello-world

    - sleep 10
    - docker compose ps
    - echo "Деплой успешно завершен!"
  only:
    - master