services:
  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: unless-stopped
    working_dir: /promtail
    volumes:
      - ./docker/override-compose/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - promtail_data:/promtail
      - ./app:/app
    command: -config.file=/etc/promtail/config.yaml
    ports:
      - "9080:9080"
    depends_on:
      loki:
        condition: service_started
    networks:
      - payout-service_network

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    working_dir: /loki
    volumes:
      - ./docker/override-compose/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://loki:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 70s
    networks:
      - payout-service_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    working_dir: /prometheus
    environment:
      - PROMETHEUS_STORAGE_TSDB_PATH=/prometheus
      - PROMETHEUS_STORAGE_TSDB_RETENTION_TIME=7d
    volumes:
      - ./docker/override-compose/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yaml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "9090:9090"
    depends_on:
      - app
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://prometheus:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - payout-service_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    working_dir: /grafana
    env_file:
      - ./docker/override-compose/.grafana-env
    volumes:
      - ./docker/override-compose/grafana-datasources.yaml:/etc/grafana/provisioning/datasources.yaml:ro
      - ./docker/override-compose/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:rw
      - ./docker/override-compose/dashboards-grafana:/etc/grafana/provisioning/dashboards:rw
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://grafana:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_started
    networks:
      - payout-service_network

volumes:
  promtail_data:
  loki_data:
  prometheus_data:
  grafana_data: