all:
  children:
    bootstrap:
      hosts:
        server1-bootstrap:
          ansible_host: 85.117.234.244
          ansible_user: root
          ansible_ssh_private_key_file: "{{inventory_dir}}/../files/root_id_rsa"
          ansible_python_interpreter: /usr/bin/python3.12
    prod:
      hosts:
        server1-prod:
          ansible_host: 85.117.234.244
          ansible_user: root
          ansible_ssh_private_key_file: "{{inventory_dir}}/../files/root_id_rsa"
          ansible_python_interpreter: /usr/bin/python3.12
    dev: {}
    staging: {}