services:
  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    environment:
      REGISTRATION_TOKEN: ${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-config:/etc/gitlab-runner
      - ./register.sh:/usr/local/bin/register-runner.sh:ro
    command: sh -c "
        chmod +x /usr/local/bin/register-runner.sh &&
        /usr/local/bin/register-runner.sh &&
        gitlab-runner run
      "