- name: Get project registration token via API
  uri:
    url: "https://gitlab.com/api/v4/projects/farzXr%2Fpayout-service/runners_token"
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"  # Нужен токен с scope 'api'
    status_code: 200
    validate_certs: yes
  register: project_token
  delegate_to: localhost
  run_once: true
  ignore_errors: yes