- name: Include authenticate task
  ansible.builtin.import_tasks: authenticate.yml
  tags: authenticate

- name: Include secret task
  ansible.builtin.import_tasks: secret.yml
  tags: secret

- name: Include runner task
  ansible.builtin.import_tasks: runner.yml
  tags: runner

- name: Include register task
  ansible.builtin.import_tasks: register.yml
  tags: register