$ANSIBLE_VAULT;1.1;AES256
66616337656239343263636665306363613163313566643064393932333365633837333662656665
3235313461663331626462306534356232313264383731330a656135343437613064666637636261
35356130396131323231366464393238353732323134323636643964363166316439366465336131
6165386264333232310a323136333261313435616530373666373138383162346430396461373633
65346633663161653062643865613232376538353863643266326530386635316335333132323030
39343332643066613432663338623832663236346538356435333931383030326537343839353939
633830613530653665386366666266316565
