- name: Include requirements.yml task
  ansible.builtin.import_tasks: requirements.yml
  tags: requirements

- name: Include install task
  ansible.builtin.import_tasks: install.yml
  tags: install

- name: Include configure task
  ansible.builtin.import_tasks: configure.yml
  tags: configure

- name: Include debug task
  ansible.builtin.import_tasks: debug.yml
  tags: debug