    - name: Get GitLab API token from Vault
      delegate_to: localhost
      run_once: true
      community.hashi_vault.hashivault_read:
        url: https://127.0.0.1:8200
        path: "secret/data/gitlab/token-access"
        token: "{{ vault_login.auth.client_token }}"
      register: vault_secret
      no_log: true