    - name: Get GitLab API token from Vault
      delegate_to: localhost
      run_once: true
      community.hashi_vault.vault_read:
        url: https://127.0.0.1:8200
        path: "secrets/data/gitlab/token-api"
        token: "{{ auth_token }}"
      register: vault_secret
      no_log: true

    - name: Extract gitlab-token
      set_fact:
        gitlab_access_token: "{{ vault_secret.data.data.data.value }}"
      no_log: true